### 导入

In [1]:
import numpy as np

### 1.如何创建数组
* ndarray: 多维数据结构，一种新的数据类型,nd表示n-dimention
* ufunc: 配套的很多函数

In [5]:
# 实用list数据初始化一个ndarray
a = np.array([1,2,3])
print(a)
b = np.array([1.1,2.2,3.3])
print(b)
c = np.array([[1,2,3],[4,5,6]])
print(c)

[1 2 3]
[1.1 2.2 3.3]
[[1 2 3]
 [4 5 6]]


In [6]:
a = np.array([1,2,'3']) # ndarray里数据需要为统一类型，为自动转换；list不要求
a

array(['1', '2', '3'], dtype='<U11')

In [7]:
a = np.array([1,2,3.3])
a

array([1. , 2. , 3.3])

### 使用arrange函数
#### 为了创建列表，NumPy提供了和range类似的函数，通过指定开始值、终值和步长来创建一维数组，注意数组不包括终值。

In [22]:
a = np.arange(1,100,2) #步长为2
print(a)
b = np.arange(0,3,0.3) #步长可以接收浮点数
print(b)

##arange函数可以看做是range函数的数组版，能生成一个一维数组，然后可以用reshape函数将一维数组改变成想要的形状，原数组的shape保持不变。
b = a.reshape(5,-1) # -1表示自动计算,即50/5=10
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7]
[[ 1  3  5  7  9 11 13 15 17 19]
 [21 23 25 27 29 31 33 35 37 39]
 [41 43 45 47 49 51 53 55 57 59]
 [61 63 65 67 69 71 73 75 77 79]
 [81 83 85 87 89 91 93 95 97 99]]


### 2.如何访问数组里数据？
#### 数组元素的存取方法和Python中list的标准方法相同

In [34]:
a = np.arange(10)
print(a)
a[5] #访问某一个，用整数作为下标可以获取数组中的某个元素
a[3:5] #片段，用范围作为下标获取数组的一个切片，包括a[3]不包括a[5]
a[:5] #省略开始下标，表示从a[0]开始
a[:-1] ## 下标可以使用负数，表示从数组后往前数
a[2:4] = 100,101 #下标还可以用来修改元素的值
print(a)
a[1:-1:2] #范围中的第三个参数表示步长，2表示隔一个元素取一个元素
a[::-1] #省略范围的开始下标和结束下标，步长为-1，整个数组头尾颠倒
a[5:1:-2] #步长为负数时，开始下标必须大于结束下标

[0 1 2 3 4 5 6 7 8 9]
[  0   1 100 101   4   5   6   7   8   9]


array([  5, 101])

### 3.数组的共享数据空间问题
#### 和Python的列表序列不同，通过下标范围获取的新的数组是原始数组的一个视图。它与原始数组共享同一块数据空间

In [36]:
a = np.arange(10)
b = a[3:7] # 通过下标范围产生一个新的数组b，b和a共享同一块数据空间
b

array([3, 4, 5, 6])

In [37]:
b[2] = -1 # 将b的第2个元素

In [39]:
a # a对应位置元素也修改了

array([ 0,  1,  2,  3,  4, -1,  6,  7,  8,  9])

### 如何避免
#### 使用整数序列（列表或者数组）作为下标获得的数组不和原始数组共享数据空间。

In [45]:
x = np.arange(10,1,-1)
print(x)
x[[3,3,1,8]] #使用列表 获取x中的下标为3, 3, 1, 8的4个元素，组成一个新的数组
b =  x[np.array([3,3,-3,8])] #使用数组下标可以是负数
print(b)
b[2] = 100
x # 由于b和x不共享数据空间，因此x中的值并没有改变
x[[3,5,1]] = -1, -2, -3 # 整数序列下标也可以用来修改元素的值

[10  9  8  7  6  5  4  3  2]
[7 7 4 2]


### 深度复制

In [49]:
#数组深度复制
a = np.arange(10)
b = a[3:7] # 通过下标范围产生一个新的数组b，b和a共享同一块数据空间
d = b.copy()
d[2]=-1 # 将b的第2个元素修改
print(d)
print(b) #未变
print(a) #未变

[ 3  4 -1  6]
[3 4 5 6]
[0 1 2 3 4 5 6 7 8 9]


### 4.多维数组
#### 多维数组的存取和一维数组类似，因为多维数组有多个轴，因此它的下标需要用多个值来表示

In [51]:
nd = np.arange(0,60).reshape(6,10)
nd

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [53]:
nd[1:3,3:5]

array([[13, 14],
       [23, 24]])

### 5.数组的切分与拼接

#### 5.1切分

In [56]:
a = np.arange(9)
b = np.split(a,3) #将数组分为三个大小相等的子数组
print(b)
b = np.split(a,[4,7]) # 4的位置切一刀，7的位置切一刀
print(b)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [74]:
harr = np.floor(10*np.random.random((2,6))) #0~1之间的随机数，行2个,列6个; 对每一个取“地板”值
print(harr)
np.hsplit(harr,3) # 地平线，把它分三段

[[1. 8. 9. 8. 8. 2.]
 [7. 8. 7. 9. 7. 6.]]


[array([[1., 8.],
        [7., 8.]]), array([[9., 8.],
        [7., 9.]]), array([[8., 2.],
        [7., 6.]])]

In [76]:
a = np.arange(16).reshape(4,4)
b = np.vsplit(a,2) #垂线，把它分两段
b

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

#### 5.2拼接数组
#### 建构不同的数组，多个数组可以按照不同的轴合在一起

In [80]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.concatenate((a,b)) #沿轴 0 连接两个数组
np.concatenate((a,b), axis = 1) #沿轴 1 连接两个数组

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### 6.NumPy提供的数组的函数ufunc
#### ufunc是universal function的缩写，它是一种能对数组的每个元素进行操作的函数。许多ufunc函数都是在C语言级别实现的，因此它们的计算速度非常快。

#### 6.1数组之间的四则运算

In [82]:
#数组间运算，是每个位置的元素对应分别计算,形状需要一样
x=np.array([1,2,3])
y=np.array([5,6,7])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[ 6  8 10]
[-4 -4 -4]
[ 5 12 21]
[0.2        0.33333333 0.42857143]


#### 6.2 ufunc常用函数
**一元ufunc**
* ceil(x): 向上最接近的整数，参数是 number 或 array
* floor(x): 向下最接近的整数，参数是 number 或 array
* rint(x): 四舍五入，参数是 number 或 array
* negative(x): 元素取反，参数是 number 或 array
* abs(x)：元素的绝对值，参数是 number 或 array
* square(x)：元素的平方，参数是 number 或 array
* aqrt(x)：元素的平方根，参数是 number 或 array
* sign(x)：计算各元素的正负号, 1(正数)、0（零）、-1(负数)，参数是 number 或 array
* modf(x)：将数组的小数和整数部分以两个独立数组的形式返回，参数是 number 或 array
* isnan(x): 判断元素是否为 NaN(Not a Number)，返回bool，参数是 number 或 array
**二元ufunc**
* add(x, y): 元素相加，x + y，参数是 number 或 array
* subtract(x, y): 元素相减，x – y，参数是 number 或 array
* multiply(x, y): 元素相乘，x * y，参数是 number 或 array
* divide(x, y): 元素相除，x / y，参数是 number 或 array
* floor_divide(x, y): 元素相除取整数商(丢弃余数)，x // y，参数是 number 或 array
* mod(x, y): 元素求余数，x % y，参数是 number 或 array
* power(x, y): 元素求次方，x ** y，参数是 number 或 array
* equal(x1, x2 [, y]) : y = x1 == x2
* not_equal(x1, x2 [, y]) : y = x1 != x2
* less(x1, x2, [, y]) : y = x1 < x2
* less_equal(x1, x2, [, y]) : y = x1 <= x2
* greater(x1, x2, [, y]) : y = x1 > x2
* greater_equal(x1, x2, [, y]) : y = x1 >= x2

### 7.NumPy提供了其他的函数库
**比较运算**
* allclose(a, b[, rtol, atol, equal_nan]) 如果两个数组在容差范围内在元素方面相等，则返回True。
* isclose(a, b[, rtol, atol, equal_nan]) 返回一个布尔数组，其中两个数组在容差范围内是元素相等的。
* array_equal(a1, a2) 如果两个数组具有相同的形状和元素，则为真，否则为False。
* array_equiv(a1, a2) 如果输入数组的形状一致且所有元素相等，则返回True。
* greater(x1, x2, /[, out, where, casting, …]) 逐个元素方式返回（x1> x2）的真值。
* greater_equal(x1, x2, /[, out, where, …]) 逐个元素方式返回（x1> = x2）的真值。
* less(x1, x2, /[, out, where, casting, …]) 逐个元素方式返回
* less_equal(x1, x2, /[, out, where, casting, …]) 逐个元素方式返回
* equal(x1, x2, /[, out, where, casting, …]) 逐个元素返回（x1 == x2）。
* not_equal(x1, x2, /[, out, where, casting, …]) 逐个元素返回 Return (x1 != x2)。

**三角函数**
* sin(x, /[, out, where, casting, order, …]) 逐个元素运算三角正弦函数。
* cos(x, /[, out, where, casting, order, …]) 逐个元素运算三角余弦函数。
* tan(x, /[, out, where, casting, order, …]) 逐个元素运算三角正切函数。
* arcsin(x, /[, out, where, casting, order, …]) 逐个元素运算三角反正弦函数。
* arccos(x, /[, out, where, casting, order, …]) 逐个元素运算三角反余弦函数。
* arctan(x, /[, out, where, casting, order, …]) 逐个元素运算三角反正切函数。
* hypot(x1, x2, /[, out, where, casting, …]) 给定直角三角形的“腿”，返回它的斜边。
* arctan2(x1, x2, /[, out, where, casting, …]) 元素弧切线x1/x2正确选择象限。
* degrees(x, /[, out, where, casting, order, …]) 将角度从弧度转换为度数。
* radians(x, /[, out, where, casting, order, …]) 将角度从度数转换为弧度。
* unwrap(p[, discont, axis]) 通过将值之间的差值更改为2*pi补码来展开。
* deg2rad(x, /[, out, where, casting, order, …]) 将角度从度数转换为弧度。
* rad2deg(x, /[, out, where, casting, order, …]) 将角度从弧度转换为度数。

**求总和, 求乘积, 求差异**
* prod(a[, axis, dtype, out, keepdims]) 返回给定轴上的数组元素的乘积。
* sum(a[, axis, dtype, out, keepdims]) 给定轴上的数组元素的总和。
* nanprod(a[, axis, dtype, out, keepdims]) 返回给定轴上的数组元素的乘积。
* nansum(a[, axis, dtype, out, keepdims]) 返回给定轴上的数组元素的总和。
* cumprod(a[, axis, dtype, out]) 返回给定轴上元素的累积乘积。
* cumsum(a[, axis, dtype, out]) 返回给定轴上元素的累积和。
* nancumprod(a[, axis, dtype, out]) 返回给定轴上的数组元素的累积乘积
* nancumsum(a[, axis, dtype, out]) 返回给定轴上的数组元素的累积和。
* diff(a[, n, axis]) 计算沿给定轴的第n个离散差。
* ediff1d(ary[, to_end, to_begin]) 数组的连续元素之间的差异。
* gradient(f, varargs, *kwargs) 返回N维数组的渐变。
* cross(a, b[, axisa, axisb, axisc, axis]) 返回两个（数组）向量的叉积。
* trapz(y[, x, dx, axis]) 沿给定的轴积分使用复合梯形规则运算。

**平均数和差异**
* median(a[, axis, out, overwrite_input, keepdims]) 沿指定轴计算中值。
* average(a[, axis, weights, returned]) 计算沿指定轴的加权平均。
* mean(a[, axis, dtype, out, keepdims]) 沿指定的轴计算算术平均值。
* std(a[, axis, dtype, out, ddof, keepdims]) 计算沿指定轴的标准偏差。
* var(a[, axis, dtype, out, ddof, keepdims]) 计算沿指定轴的方差。
* nanmedian(a[, axis, out, overwrite_input, …]) 在忽略NAS的情况下，沿指定的轴计算中值。
* nanmean(a[, axis, dtype, out, keepdims]) 计算沿指定轴的算术平均值，忽略NAS。
* nanstd(a[, axis, dtype, out, ddof, keepdims]) 计算指定轴上的标准偏差，而忽略NAS。
* nanvar(a[, axis, dtype, out, ddof, keepdims]) 计算指定轴上的方差，同时忽略NAS。

### NumPy函数比普通函数的优势

In [89]:
import time
import math
x = [i * 0.001 for i in range(1000000)] #百度python数组创建语法[for in range]
start = time.process_time()
for i,t in enumerate(x):
    x[i] = math.sin(t) #python自带的函数
print("math.sin:", time.process_time()-start)

math.sin: 0.328125


In [92]:
x = [i * 0.001 for i in range(1000000)]
x = np.array(x) # x已经转变为 ndarray对象
start = time.process_time()
np.sin(x) #numpy的函数
print ("numpy.sin:", time.process_time() - start)

numpy.sin: 0.03125


### 8.NumPy的文件读取函数
从文件里读取数据直接构建ndarray，或者把结果保存
* np.loadtxt(FILENAME, dtype=int, delimiter=' ')
* np.savetxt(FILENAME, a, fmt="%d", delimiter=",")

In [109]:
a = np.arange(0,12,0.5).reshape(4,-1)
print(a)
np.savetxt("a.txt", a) # 缺省按照'%.18e'格式保存数据，以空格分隔
np.loadtxt("a.txt")

[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]


array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5, 11. , 11.5]])

In [111]:
np.savetxt("a.txt", a, fmt="%d", delimiter=",") #改为保存为整数，以逗号分隔
np.loadtxt("a.txt",delimiter=",") # 读入的时候也需要指定逗号分隔

array([[ 0.,  0.,  1.,  1.,  2.,  2.],
       [ 3.,  3.,  4.,  4.,  5.,  5.],
       [ 6.,  6.,  7.,  7.,  8.,  8.],
       [ 9.,  9., 10., 10., 11., 11.]])

In [113]:
 a = np.arange(0,12).reshape(3,4)
np.savetxt("a.txt", a, fmt='%10.5f')
b = np.loadtxt("a.txt")
b

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])